{
 "title": "Stormwall Stats",
 "description": "API statistics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Активные атаки",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stormwall_attack_severity{job=\"stormwall-exporter\"}",
     "legendFormat": "{{attack_type}} - {{attack_target}}"
    }
   ]
  },
  {
   "title": "L3 Скорость трафика (IN/OUT)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stormwall_l3_traffic_out", "legendFormat": "OUT" },
    { "expr": "stormwall_l3_traffic_in", "legendFormat": "IN" }
   ]
  },
  {
   "title": "L3 Процентиль трафика (IN/OUT)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "stormwall_l3_percentile_out", "legendFormat": "OUT_percentile" },
    { "expr": "stormwall_l3_percentile_in", "legendFormat": "IN_percentile" },
    { "expr": "stormwall_l3_traffic_out", "legendFormat": "OUT" },
    { "expr": "stormwall_l3_traffic_in", "legendFormat": "IN" }
   ]
  },
  {
   "title": "ТОП5 Объём всего трафика",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, stormwall_l7_traffic_total{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Начало активной атаки",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stormwall_attack_start_time{job=\"stormwall-exporter\"}",
     "legendFormat": "{{attack_target}}"
    }
   ]
  },
  {
   "title": "ТОП5 Трафик (входящий)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(5, stormwall_l7_traffic_in{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "ТОП5 Трафик (исходящий)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(5, stormwall_l7_traffic_out{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "ТОП5 Объём входящего трафика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, stormwall_l7_traffic_in_total{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Процент кешированного трафика",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(stormwall_l7_traffic_cached_percent{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Процент некешированного трафика",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(stormwall_l7_traffic_cache_bypassed_percent{job=\"stormwall-exporter\"}) * 100",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "ТОП5 Кешированный Трафик ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(5, stormwall_l7_traffic_cached{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "ТОП5 Некешированный Трафик ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(5, stormwall_l7_traffic_cached_bypass{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Количество кешированного трафика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, stormwall_l7_traffic_cached_total{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Количество некешированного трафика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, stormwall_l7_traffic_cache_bypassed_total{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Общий процент по эндпоинтам rps(total)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stormwall_l7_traffic_total_rps{job=\"stormwall-exporter\", domain=~\".*\\\\.sigma\\\\.ru\"})",
     "legendFormat": "*.sigma.ru"
    },
    {
     "expr": "stormwall_l7_traffic_total_rps{job=\"stormwall-exporter\", domain!=\".*\\\\.sigma\\\\.ru\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Общий процент по эндпоинтам mb\\s",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (avg_over_time(stormwall_l7_traffic_in{job=\"stormwall-exporter\", domain=~\".*\\\\.sigma\\\\.ru\"}[$__range])) / scalar(sum(avg_over_time(stormwall_l7_traffic_in{job=\"stormwall-exporter\"}[$__range]))))",
     "legendFormat": "*.sigma.ru"
    },
    {
     "expr": "100 * (sum by (domain) (avg_over_time(stormwall_l7_traffic_in{job=\"stormwall-exporter\", domain!~\".*\\\\.sigma\\\\.ru\"}[$__range])) / scalar(sum(avg_over_time(stormwall_l7_traffic_in{job=\"stormwall-exporter\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRORS rps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "stormwall_l7_traffic_errors_rps{job=\"stormwall-exporter\"} > 0.5",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Blocked/Permited rps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(3, stormwall_l7_traffic_permitted_rps{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}} - permitted"
    },
    {
     "expr": "topk(3, stormwall_l7_traffic_blocked_rps{job=\"stormwall-exporter\"})",
     "legendFormat": "{{domain}} - blocked"
    }
   ]
  }
 ]
}